name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]        
permissions:
  contents: write
jobs:
  Release-solution-NewAppClean:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      #You can specify the solution name here
      solution_name: NewApp
      #Update your values here
      BUILD_ENVIRONMENT_URL: https://orgb470c715.crm11.dynamics.com/
      PRODUCTION_ENVIRONMENT_URL: https://org6b012c23.crm11.dynamics.com/
      CLIENT_ID: 717226da-1708-458e-b56a-559e3a991cc3
      TENANT_ID: 21f86a55-b21d-41aa-b173-656614ff35d9      
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
